### PR TITLE
fixed issue with precision

### LINKED ISSUE #48: Precision issue
I am not sure if this is an issue. But this might affect the algorithm (floating point). I tried the code below with vector of size 8. 

```
wt.corr(1:8, 2:9, rep(0, 8))
wt.corr(1:8, 2:9, rep(1, 8))
```

One thing we can do is completely avoid weights with a weight of 0.

### PR DESCRIPTION
**Pull request by thevaachandereng**
I honestly did not see the else if statement. I am not sure what I was thinking when I coded this up. It looks good now. closed #48

### CODE REVIEW

File: tests/testthat/test_wt_corr.R [hunk 1]
```diff
@@ -1,6 +1,6 @@
 context("")
 test_that("the weighted correlation is", {
-  expect_equal(wt.corr(1:8, 2:9, rep(0, 8)), 1, tolerance=1e-4)
```
Comment (agitter) [inline tests/testthat/test_wt_corr.R]: We no longer need the `tolerance` here, but let's keep it in mind for other test cases.

Comment (thevaachandereng) [reply tests/testthat/test_wt_corr.R]: I remember learning this when I was first introduced to testthat package. There is a function expect_identical() as well. I am not sure what the tolerance level is preset.
